import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientProviders from "@/utils/ClientProviders";
import Header from "@/components/header/Header";
import FirebaseAuthProvider from "@/utils/FirebaseAuthProvider";
import PaymentProvider from "@/utils/PaymentProvider";
import CreditsProvider from "@/utils/CreditsProvider";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientProviders>
      <html lang="en">
        <body className={inter.className}>
          <FirebaseAuthProvider>
            <PaymentProvider>
              <CreditsProvider>
                <Header />
                {children}
                <Toaster />
              </CreditsProvider>
            </PaymentProvider>
          </FirebaseAuthProvider>
        </body>
      </html>
    </ClientProviders>
  );
}
